spring:
  application:
    name: zuul-gateway
server:
  port: 7000
eureka:
  client:
     serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#zuul:
#  routes:
#    hello:
#      path: /hello
#      serviceId: eureka-client