spring:
  application:
    name: eureka-server
---
spring:
  profiles: server1
server:
  port: 8761
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
---
spring:
  profiles: server2
server:
  port: 8762
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/