spring:
  application:
    name: config-server
  cloud:
     config:
      server:
        git:
          uri: https://github.com/xssxhjw/spring-cloud-demo/
          search-paths: config-repo
server:
  port: 8765
management:
  security:
     enabled: false
#eureka:
#  client:
#     serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
