spring:
  application:
    name: config-server
  cloud:
     config:
      server:
        git:
          uri: https://github.com/ityouknow/spring-cloud-examples/
          search-paths: config-repo
server:
  port: 8765
#eureka:
#  client:
#     serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
